name: Deploy via ftp
on: 
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  deploy:
    name: Upload via ftp
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Upload ftp
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        options: "--delete --asci --only-newer"
